server:
  port: 8080

spring:
  application:
    name: netty-turn-server
  datasource:
    url: jdbc:sqlite:data/turnserver.db
    driver-class-name: org.sqlite.JDBC
    username: 
    password: 
    hikari:
      maximum-pool-size: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-init-sql: |
        PRAGMA journal_mode=WAL;
        PRAGMA synchronous=NORMAL;
        PRAGMA cache_size=10000;
        PRAGMA foreign_keys=ON; 
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jpa:
    database-platform: org.sqlite.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          # SQLite specific settings for better performance
          time_zone: UTC
        # Enable batch operations
        order_inserts: true
        order_updates: true
        batch_size: 20
  security:
    user:
      name: admin
      password: admin123
turn:
  server:
    port: 3478
    realm: "turn.example.com"
    secret: "myTurnSecret123"
    external-ip: "127.0.0.1"
    min-port: 49152
    max-port: 65535
stun:
  server:
    port: 3478
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
logging:
  level:
    com.example.turnserver: DEBUG
    io.netty: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"